# Generated by Django 5.0.6 on 2024-07-08 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition', models.BigIntegerField(verbose_name='Requisición')),
                ('entrydate', models.DateField(verbose_name='Fecha de Entrada')),
                ('observation', models.TextField(blank=True, max_length=200, null=True, verbose_name='Observacion')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
            },
        ),
        migrations.CreateModel(
            name='DetalleEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(default=0)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos.insumos')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrada.entrada')),
            ],
            options={
                'verbose_name': 'Detalle de Entrada',
                'verbose_name_plural': 'Detalle de Entradas',
            },
        ),
    ]
