# Generated by Django 5.0.6 on 2024-07-08 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumos', '0001_initial'),
        ('solicitante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition', models.BigIntegerField(verbose_name='Requisición')),
                ('applicationdate', models.DateField(verbose_name='Fecha de Solicitud')),
                ('shipmentdate', models.DateField(verbose_name='Fecha de Despacho')),
                ('observation', models.TextField(blank=True, max_length=200, null=True, verbose_name='Observacion')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitante.solicitante', verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='DetalleSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(default=0)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos.insumos')),
                ('Solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud.solicitud')),
            ],
            options={
                'verbose_name': 'Detalle de Solicitud',
                'verbose_name_plural': 'Detalle de Solicitud',
            },
        ),
    ]
