# Generated by Django 5.0.6 on 2024-07-08 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre Cargo')),
                ('description', models.CharField(blank=True, max_length=80, null=True, verbose_name='Descripcion Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Servicio')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion del Servicio')),
                ('numberofemployers', models.IntegerField(blank=True, null=True, verbose_name='Numeros de Trabjadores')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=80, verbose_name='Nombres')),
                ('lastname', models.CharField(max_length=80, verbose_name='Apellidos')),
                ('birthofdate', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitante.cargo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitante.servicio')),
            ],
            options={
                'verbose_name': 'Solicitante',
                'verbose_name_plural': 'Solicitantes',
            },
        ),
    ]
